---
# tasks file for nginx
- name: install tools
  apt:
    pkg:
      - python-httplib2
    state: present
  tags: packages

- name: install nginx
  apt: name=nginx state=present
  tags: packages

- name: configure nginx sites
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/{{ item.key }}
    mode: '0644'
  with_dict: "{{ sites }}"
  notify: restart nginx

# get list of active sites
- name: get active sites
  shell: ls -1 /etc/nginx/sites-enabled
  changed_when: "active.stdout_lines != sites.keys()"
  register: active
  tags: configure

#delete (deactivate) sites which are not active
- name: de-activate nginx sites
  file: path=/etc/nginx/sites-enabled/{{ item }} state=absent
  with_items: active.stdout_lines
  when: item not in sites
  notify: restart nginx

- name: enable nginx sites
  file: src=/etc/nginx/sites-available/{{ item.key }} dest=/etc/nginx/sites-enabled/{{ item.key }} state=link
  with_dict: "{{ sites }}"
  notify: restart nginx

- name: ensure nginx is running
  service: name=nginx state=started enabled=yes
