---
# tasks file for apache2
- name: install web components
  apt:
    pkg:
    - apache2
    - libapache2-mod-wsgi
    state: present
  tags: packages

- name: ensure mod_wsgi enabled
  apache2_module: state=present name=wsgi
  notify: restart apache2

- name: de-activate default apache site
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify: restart apache2

- name: activate demo apache site
  file: src=/etc/apache2/sites-available/demo.conf dest=/etc/apache2/sites-enabled/demo.conf state=link
  notify: restart apache2

- name: ensure web server is running
  service: name=apache2 state=started enabled=yes
